name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    # install and cache dependencies
    - name: Install boost
      run: sudo apt-get install libboost-all-dev
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

  build-windows:

   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: choco install boost-msvc-14.2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: cd build && ctest
