name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    # install and cache dependencies
    - name: Install boost
      run: sudo apt-get install libboost-all-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

  build-windows:
   runs-on: windows-latest
   env:
     BOOST_ROOT: C:\local\boost_1_74_0
     BOOST_LIBRARYDIR: C:\local\boost_1_74_0\lib64-msvc-14.2\    
   steps:
    - uses: actions/checkout@v2
    - name: Cache Boost
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: C:\local\boost_1_74_0
        key: ${{runner.os}}-boost    
    - name: Install Boost
      if: steps.cache-boost.cache-hit != 'true'
      run: choco install -y boost-msvc-14.2
      
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
