name: Publish Documentation
on:
  push:
    branches: 
      - master
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Doxygen Action
         uses: mattnotmitt/doxygen-action@v1.1.0
         with:
           doxyfile-path: "./Doxyfile"
           working-directory: "."
       - name: Doxybook
         run: |
           chmod +x doxygentomd.sh
           ./doxygentomd.sh
       - name: Deploy Docs
         uses: mhausenblas/mkdocs-deploy-gh-pages@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           CUSTOM_DOMAIN: playerlink.derangedsenators.me   
