//
// Created by hanzalah on 15/11/2020.
//

#ifndef PLAYERLINK_CORE_NETCONFIG_H
#define PLAYERLINK_CORE_NETCONFIG_H

#define DEFAULT_TCP_PORT 270500
#define DEFAULT_UDP_PORT 200800
#define OUT_BUFFER_SIZE 4096
#define SLEEP_DELAY 10
#define MAX_CLIENTS 8

#endif //PLAYERLINK_CORE_NETCONFIG_H
